# x86
STAGING_DIR     =
BIN             =
LIBEXEC         =
CC              = gcc
CPP             = g++
STRIP           = strip
RM              = rm
PLATFORM        = x86
TARGET_DIR      = .
MY_CFLAGS       =

include rules.mk
